name: ci
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Configure binary cache
        uses: cachix/cachix-action@v14
        with:
          name: fablab-altmuehlfranken
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Install nixos-rebuild helper
        run: nix-env --quiet -j8 -iA nixos-rebuild

      - name: Build configuration
        run: nixos-rebuild build --flake .#fablab
