name: ci
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          build-mount-path: '/nix'
          root-reserve-mb: 8192
          swap-size-mb: 1024
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Attic cache
        uses: ryanccn/attic-action@v0
        with:
          endpoint: https://attic.fablab-altmuehlfranken.de
          cache: fablab
          token: ${{ secrets.ATTIC_AUTH_TOKEN }}

      - name: Build configuration
        run: nix build .#nixosConfigurations.fablab.config.system.build.toplevel

  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
