name: ci
on:
  workflow_dispatch:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          build-mount-path: '/nix'
          root-reserve-mb: 8192
          swap-size-mb: 1024
          remove-android: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-dotnet: 'true'
          remove-haskell: 'true'
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Install update-nix-fetchgit
        run: |
          nix-channel --add https://nixos.org/channels/nixpkgs-unstable
          nix-channel --update

          nix-env -iA nixpkgs.attic-client

      - name: Configure attic
        run: |
          attic login --set-default $CACHE $ENDPOINT $TOKEN
        env:
          ENDPOINT: https://attic.fablab-altmuehlfranken.de
          CACHE: fablab
          TOKEN: ${{ secrets.ATTIC_AUTH_TOKEN }}

      - name: Snapshot state of nix store
        run: nix path-info --all --json > /tmp/store-paths

      - name: Build configuration
        run: nix build .#nixosConfigurations.fablab.config.system.build.toplevel

      - name: Push derivations to cache
        run: .github/push-derivations.sh
        env:
          CACHE: fablab

  shellcheck:
    runs-on: ubuntu-latest
    name: Shellcheck
    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master

